### ISSUE TITLE
example of how to receive on a channel

### ISSUE THREAD

**Issue by glycerine** [stevedonovan/luar#22]
I see hints in the luar.go code that channels are supported, but I don't fully get how to do that in lua code.  If it isn't too much trouble, a simple example of how to send from go on a channel and receive in lua (and vice-versa) would be super helpful.

Thanks!

Jason

**Comment by stevedonovan** [comment]
They are hints because it didn't fly! Naively thought  that one could drive
a Lua coroutine from a Go goroutine but Lua is not reentrant. Would need to
run a separate Lua state in a go routine only communicating with other Lua
code through channels and (probably) shared aliases to Go objects (which
would need mutexes). I'll have a look at that when I'm back at my machines

**Comment by glycerine** [comment]
Ah. Perhaps Luvit https://github.com/luvit/luvit could be of help.

**Comment by stevedonovan** [comment]
Luvit is pretty much a NodeJs clone so it's all about callback soup.  A
project to follow here is Lua Lanes which has independent Lua states
communicating on channels. Share-nothing is easier to think about I find.

**Comment by Ambrevar** [comment]
Working on this...

@stevedonovan Can you explain what you mean by "drive a Lua coroutine from a Go goroutine"?

**Comment by stevedonovan** [comment]
Lua (as you know) is fundamentally single-threaded. But coroutines can be driven by an event scheduler and an effective illusion of synchronous multi-threading is created - e.g the way COPAS works with LuaSocket. The trouble with goroutines is that they are sometimes backed by an OS thread, sometimes not  - this is also their beauty (much more scalable). You can safely have a Lua state per goroutine, but then Lua state cannot be shared and it has to move around through messaging. Then you have the marshalling problem, which Lua Lanes solves for basic Lua types. A native Go implementation of Lua has some advantages here. I think it's worth really thinking about this because it would be fantastic for the Lua/Go ecosystem.

**Comment by Ambrevar** [comment]
Hmmm, so if I understand correctly, your goal was to "parallelize" Lua coroutines by running each of them on individual goroutines? That is problematic indeed, considering the non-reentrant nature of Lua states.

I believe, however, that it would be as cool as it would be complicated to implement... Doesn't it go beyond the goals of Luar?

**Comment by stevedonovan** [comment]
Ah yes - and not entirely sure it can be done robustly!  But separate Lua states would always be cool.

As for project scope, I tend to agree with you - it is a reflection-based Lua/Go interface, and should probably stick to doing that well. 

One could imagine each Lua state having a proxy to some shared Go data, but it would probably be a mess of mutexes.

**Comment by Ambrevar** [comment]
OK, then I'll scrap your channel draft (the `channel_*` functions and `GoLua`) and implement a straightforward conversion. My first test looks good and simple.

**Comment by stevedonovan** [comment]
Good idea! Stuff that doesn't work well (or at all) shouldn't be in the public interface.

**Comment by Ambrevar** [comment]
Merged: https://github.com/stevedonovan/luar/commit/68e746ca8777572f7e1caa6adc33adcdd64d0138
