### ISSUE TITLE
Nested structure methods can not be found

### ISSUE THREAD

**Issue by liyonglion** [stevedonovan/luar#43]
```
type String string

func (self String) String() string {
	return string(self)
}

type Second struct {
	Name String
}
type Person struct {
	SecondName Second
	Age        int
}

func main() {
	const test = `
	print(user.SecondName.Name.String())
`

	L := luar.Init()
	defer L.Close()

	user := &Person{SecondName: Second{"lion"}, Age: 46}

	luar.Register(L, "", luar.Map{
		"user": user,
	})

	err := L.DoString(test)
	if err != nil {
		fmt.Println(err)
	}
}
```
run this , It show error:
`[string "..."]:2: attempt to call field 'String' (a nil value)`

**Comment by Ambrevar** [comment]
Thank you for the catch. The bug comes from an unanswered design issue. Let me break it down:

When calling `GoToLuaProxy()` over a struct, the struct is (usually) not
addressable and a Lua table is created. This table has no method.

When calling `GoToLuaProxy()` over a pointer to a struct, a proxy is created and the struct methods are callable.

The flaw shows when a direct struct is inside the struct proxy, as in your example: `&Person{SecondName: Second{"lion"}, Age: 46}`.
`SecondName` is not a pointer and thus it will be returned as a Lua table without methods.

In that case however, the inner struct is addressable, so it would be possible to proxify it.

I could change the code so that proxy array/struct members are always proxified.
The would change the inner representation of the proxy value and I wonder if this would have any undesirable side effects. Any comment on that?

I've pushed the changes on the #proxy-nesting branch. Let me know what you think.

**Comment by Ambrevar** [comment]
Same thing for slices and the fix is the same.

However, the values of struct-maps and plain structs are not addressable.
The solution would be to allocate a new struct each time.
This indulges a significant performance cost however.

Proxies serve two purposes:

- Allow direct modification of the Go value from Lua code.

- Call methods.

In the case of unaddressable values, proxies are only useful for calling methods.

I suggest the following implementation instead of checking if struct/arrays are addressable:

- If the input to `GoToLuaProxy()` is a pointer to a struct/array, then proxify.

- If not a pointer and no method, then convert to a Lua table.

- If not a pointer but has methods, then allocate a new object and return a proxy to it: modifying the proxy will have no effect, but at least the methods can be called.

**Comment by liyonglion** [comment]
Thank you! It worked. I can continue to work down, thanks again. I will read your code and I do not know if I can make useful suggestions.

**Comment by Ambrevar** [comment]
Hey, I wasn't done with it! :p 
In fact my aforementioned solution is badly designed, I have been experimenting and I think I came up with a right approach for structs and arrays. Stay tuned.

**Comment by liyonglion** [comment]
very sorry. I will continue to be concerned. ths

**Comment by Ambrevar** [comment]
I have pushed some commits on the #proxy-nesting2 branch.

Here are the updated, better specified rules for converting from Go to Lua:

```
// Proxies have several uses:
//
// - Type checking in Go function calls, so variable of user-defined type are
// always profixied.
//
// - Reflexive modification of the Go data straight from the Lua code. We only
// allow this for compound types.
//
// - Call methods of user-defined types.
//
// Predeclared scalar types are never proxified as they have no methods and we
// only allow compound types to be set reflexively.
//
// Structs are always proxified since their type is always user-defined. If they
// they are not settable (e.g. not nested, not passed by reference, value of a
// map), then a copy is passed as a proxy (otherwise setting the fields from Lua
// would panic). This will not impact the corresponding Go value.
//
// Arrays are only proxified if they are settable (so that the user can set the
// Go value from the Lua side) or if they are of a user-defined type (method
// calls or function parameters). If the type user-defined but the array is not
// settable, then a proxy of a copy is made, just as for structs.
//
// Lua cannot dereference pointers and Go can only call methods over one level
// of indirection at maximum. Thus proxies wrap around values dereferenced up to
// the last pointer.
//
// Go functions can be passed to Lua. If the parameters require several levels
// of indirections, the arguments will be converted automatically. Since proxies
// can only wrap around one level of indirection, functions modifying the value
// of the pointers after one level of indirection will have no effect.
```

Please let me know if that works for you and I will merge.

**Comment by Ambrevar** [comment]
@liyonglion Any feedback?

**Comment by Ambrevar** [comment]
I have merged the change into master.
