### ISSUE TITLE
can't index slice/map returned by wrapped go method in lua code

### ISSUE THREAD

**Issue by mischief** [stevedonovan/luar#5]
hey, i'm trying to index a slice/map returned by a go method called from inside lua, but i always get this error:

```
 reflect: call of reflect.Value.Type on zero Value
```

heres a test case, maybe i'm just doing something wrong https://gist.github.com/mischief/ec3ec7a4a9a88fc353ac

**Comment by Ambrevar** [comment]
I've investigated on this issue: The OP example can be simplified to a Go function returning a struct (and not a pointer to a struct). `GoToLua` cannot proxify structs since they are not addressable, and thus the result will be a table on which no method can be called.

I believe that forcibly passing a pointer to struct to `GoToLua` makes sense, right?
From the Lua side, it will be the expected userdata on which the methods can be called.

The fix is as follows:

``` go
func GoLuaFunc(L *lua.State, fun interface{}) lua.LuaGoFunction {
	// ...
			for _, val := range resV {
			if val.Kind() == reflect.Struct {
				n := reflect.New(val.Type())
				n.Elem().Set(val)
				val = n
			}
```

**Comment by Ambrevar** [comment]
Fixed in https://github.com/stevedonovan/luar/commit/9b929c95458816862835e9ae03564af500760ac6.
